### PR TITLE
Modify x64 support to use RET rather than JMP

### PR DESCRIPTION
**Pull request by RomanHargrave**
All credit for this work goes to @Ozymandias117.

He's not been very active lately, but I figured I would open this PR as these changes 
allowed @blt4linux to go ahead.

Description of the changes as per @Ozymandias117:

```
Unforunately, 64-bit direct jumps don't work in AMD64. In order to
avoid this issue, I am pushing the address we wish to jump to on the
stack and calling RET.

Due to the same issues as JMP, using the trampoline is unlikely to be
safe in many situations. Therefore, I would recommend only using
ScopedRemove, or manually removing the hook prior to calling the
original function, instead of using a the trampoline.
```

### CODE REVIEW

**Comment by Zeex** [comment]
Great, thanks!

**Comment by Zeex** [comment]
This doesn't seem to work on WIndows though, at least for the [test program](https://github.com/Zeex/subhook/tree/master/test). It looks like MSVC generates a single jump for both `foo` and `foo_hook`, but the new jump method code is too fat to fit in 5 bytes. I think there now needs be a way to select which hook method to use on x64.

**Comment by Ozymandias117** [comment]
This is part of why I hadn't made a PR yet.

I haven't tested any of it on a Windows platform. I'd also intended to test automatically switching between the two depending on the jump size, but it could also just be a flag during construction. Finally, I'd intended to ensure that the trampoline wasn't created if we're using the PUSH/RET codepath if the trampoline contained at least a JMP. I wasn't sure if there were any other instructions that would break it.

I'm not sure of a good way to ensure that the function we're hooking is large enough to use the new hook. When writing this I was just working off of the assumption that there isn't much point in hooking a function that small, but there might be a way to get that information from the LDE.

I'd gotten it working well enough for our usecase, and stay busy enough that I had chosen not to bother cleaning it up yet.

**Comment by RomanHargrave** [comment]
@Zeex, yeah I had forgot to mention that the appveyor build failed. I was partially hoping that this didn't get merged just yet for that reason.

I had opened this PR because contact with Ozy had been very sparse, and what with his GH account being quite new I assumed it was a throwaway of sorts.

**Pull request merged**
